import type {
  Agent,
  Task,
  MemoryEntry,
  LogEntry,
  Playbook,
  ApprovalRequest,
  Project,
} from '@/lib/types';

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'agent-chief',
    name: 'Chief',
    role: 'Orchestrator',
    status: 'running',
    lastActive: '2024-01-15T10:30:00Z',
    taskCount: 142,
    successRate: 97.2,
    description: 'Entry point and final response synthesiser for all user requests.',
    tools: ['memory', 'router', 'reviewer'],
    avatarInitials: 'CH',
  },
  {
    id: 'agent-intent',
    name: 'Intent Router',
    role: 'Classifier',
    status: 'idle',
    lastActive: '2024-01-15T10:28:00Z',
    taskCount: 139,
    successRate: 99.1,
    description: 'Classifies incoming requests and routes them to specialist agents.',
    tools: ['classifier', 'memory'],
    avatarInitials: 'IR',
  },
  {
    id: 'agent-knowledge',
    name: 'Knowledge',
    role: 'Retrieval',
    status: 'idle',
    lastActive: '2024-01-15T10:25:00Z',
    taskCount: 88,
    successRate: 94.3,
    description: 'Performs semantic memory retrieval across all stored knowledge.',
    tools: ['supabase', 'embeddings', 'web_search'],
    avatarInitials: 'KN',
  },
  {
    id: 'agent-builder',
    name: 'Builder',
    role: 'Generator',
    status: 'running',
    lastActive: '2024-01-15T10:30:00Z',
    taskCount: 76,
    successRate: 91.8,
    description: 'Produces structured output: code, documents, plans, and reports.',
    tools: ['code_executor', 'file_ops', 'http_caller'],
    avatarInitials: 'BU',
  },
  {
    id: 'agent-critic',
    name: 'Critic',
    role: 'Reviewer',
    status: 'waiting',
    lastActive: '2024-01-15T10:29:00Z',
    taskCount: 64,
    successRate: 96.9,
    description: 'Reviews and QA-checks all builder output before delivery.',
    tools: ['memory', 'classifier'],
    avatarInitials: 'CR',
  },
  {
    id: 'agent-memory-writer',
    name: 'Memory Writer',
    role: 'Persistence',
    status: 'idle',
    lastActive: '2024-01-15T10:20:00Z',
    taskCount: 201,
    successRate: 99.5,
    description: 'Extracts learnings from completed tasks and persists to long-term memory.',
    tools: ['supabase', 'embeddings'],
    avatarInitials: 'MW',
  },
  {
    id: 'agent-approval',
    name: 'Approval Gate',
    role: 'Safety',
    status: 'idle',
    lastActive: '2024-01-15T09:55:00Z',
    taskCount: 23,
    successRate: 100,
    description: 'Flags and queues high-risk actions for human approval before execution.',
    tools: ['http_caller', 'supabase'],
    avatarInitials: 'AG',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-001',
    title: 'Analyse Q1 revenue data and produce summary report',
    description: 'Retrieve Q1 data from Supabase, run analysis, generate PDF report.',
    status: 'running',
    assignedAgent: 'agent-builder',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
    priority: 'high',
    projectId: 'proj-001',
    dependencies: [],
    retries: 0,
  },
  {
    id: 'task-002',
    title: 'Research latest LLM fine-tuning techniques',
    description: 'Web search + summarise top 5 papers on LoRA and QLoRA.',
    status: 'completed',
    assignedAgent: 'agent-knowledge',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T09:30:00Z',
    priority: 'medium',
    projectId: null,
    dependencies: [],
    retries: 0,
  },
  {
    id: 'task-003',
    title: 'Deploy staging environment health check',
    description: 'Ping all staging endpoints and report status.',
    status: 'failed',
    assignedAgent: 'agent-builder',
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-01-15T09:45:00Z',
    priority: 'critical',
    projectId: 'proj-002',
    dependencies: [],
    retries: 2,
  },
  {
    id: 'task-004',
    title: 'Write playbook for recurring SEO audit workflow',
    description: 'Document the 12-step SEO audit process as a reusable playbook.',
    status: 'pending',
    assignedAgent: 'agent-chief',
    createdAt: '2024-01-15T10:15:00Z',
    updatedAt: '2024-01-15T10:15:00Z',
    priority: 'low',
    projectId: null,
    dependencies: ['task-002'],
    retries: 0,
  },
];

export const MOCK_MEMORY: MemoryEntry[] = [
  {
    id: 'mem-001',
    domain: 'code',
    content: 'Next.js 15 App Router requires all server components to be async. Client components must be marked with \'use client\'.',
    tags: ['nextjs', 'react', 'architecture'],
    createdAt: '2024-01-10T14:00:00Z',
    agentSource: 'agent-memory-writer',
    relevanceScore: 0.94,
    accessCount: 12,
  },
  {
    id: 'mem-002',
    domain: 'research',
    content: 'LoRA fine-tuning with rank 8-16 achieves 90% of full fine-tune quality at 1% of VRAM cost.',
    tags: ['llm', 'fine-tuning', 'lora'],
    createdAt: '2024-01-12T09:00:00Z',
    agentSource: 'agent-knowledge',
    relevanceScore: 0.88,
    accessCount: 5,
  },
  {
    id: 'mem-003',
    domain: 'planning',
    content: 'User prefers deliverables as structured markdown with numbered sections. Always include TL;DR at top.',
    tags: ['preferences', 'output-format'],
    createdAt: '2024-01-08T11:00:00Z',
    agentSource: 'agent-memory-writer',
    relevanceScore: 0.99,
    accessCount: 34,
  },
];

export const MOCK_LOGS: LogEntry[] = [
  {
    id: 'log-001',
    level: 'info',
    message: 'Task task-001 started. Assigning to Builder agent.',
    agentId: 'agent-chief',
    agentName: 'Chief',
    taskId: 'task-001',
    timestamp: '2024-01-15T10:00:01Z',
    metadata: { attempt: 1 },
  },
  {
    id: 'log-002',
    level: 'success',
    message: 'Memory retrieval complete. Found 3 relevant entries for task-002.',
    agentId: 'agent-knowledge',
    agentName: 'Knowledge',
    taskId: 'task-002',
    timestamp: '2024-01-15T08:05:00Z',
    metadata: { entriesFound: 3, latencyMs: 142 },
  },
  {
    id: 'log-003',
    level: 'error',
    message: 'HTTP 503 from staging endpoint /api/health after 2 retries. Task failed.',
    agentId: 'agent-builder',
    agentName: 'Builder',
    taskId: 'task-003',
    timestamp: '2024-01-15T09:45:00Z',
    metadata: { statusCode: 503, retries: 2 },
  },
  {
    id: 'log-004',
    level: 'warn',
    message: 'Approval required before executing file deletion on /data/archive.',
    agentId: 'agent-approval',
    agentName: 'Approval Gate',
    taskId: null,
    timestamp: '2024-01-15T09:50:00Z',
    metadata: { riskLevel: 'high' },
  },
];

export const MOCK_PLAYBOOKS: Playbook[] = [
  {
    id: 'pb-001',
    name: 'Weekly SEO Audit',
    description: 'Full technical SEO audit: crawl errors, core web vitals, backlink check, content gaps.',
    steps: [
      'Run Screaming Frog crawl',
      'Pull Core Web Vitals from Search Console',
      'Analyse top 10 competitor backlinks',
      'Generate gap report',
      'Produce priority action list',
    ],
    domain: 'research',
    usageCount: 8,
    createdAt: '2024-01-05T00:00:00Z',
    successRate: 100,
    tags: ['seo', 'marketing', 'weekly'],
  },
  {
    id: 'pb-002',
    name: 'Code Review Pipeline',
    description: 'Automated PR review: lint, test, security scan, summary comment.',
    steps: [
      'Pull diff from GitHub PR',
      'Run ESLint and TypeScript checks',
      'Execute test suite',
      'Run Snyk security scan',
      'Post structured review comment',
    ],
    domain: 'code',
    usageCount: 22,
    createdAt: '2024-01-02T00:00:00Z',
    successRate: 95.5,
    tags: ['code', 'github', 'automation'],
  },
];

export const MOCK_APPROVALS: ApprovalRequest[] = [
  {
    id: 'apr-001',
    title: 'Delete archived data files',
    description: 'Builder agent requests deletion of 847 files in /data/archive/ older than 90 days.',
    risk: 'high',
    requestedBy: 'agent-builder',
    requestedAt: '2024-01-15T09:50:00Z',
    action: 'file_delete',
    payload: { path: '/data/archive/', fileCount: 847, olderThanDays: 90 },
    status: 'pending',
  },
  {
    id: 'apr-002',
    title: 'Send email to client list',
    description: 'Communication agent requests sending campaign email to 1,240 contacts.',
    risk: 'medium',
    requestedBy: 'agent-builder',
    requestedAt: '2024-01-15T08:30:00Z',
    action: 'email_send',
    payload: { recipientCount: 1240, templateId: 'campaign-q1' },
    status: 'pending',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    name: 'Q1 Analytics Dashboard',
    description: 'Build and deploy interactive Q1 revenue analytics dashboard for stakeholders.',
    status: 'active',
    progress: 68,
    taskCount: 12,
    completedTasks: 8,
    createdAt: '2024-01-01T00:00:00Z',
    agents: ['agent-builder', 'agent-critic', 'agent-knowledge'],
    tags: ['analytics', 'dashboard', 'q1'],
  },
  {
    id: 'proj-002',
    name: 'Infrastructure Hardening',
    description: 'Audit and harden all staging and production infrastructure endpoints.',
    status: 'active',
    progress: 35,
    taskCount: 8,
    completedTasks: 3,
    createdAt: '2024-01-08T00:00:00Z',
    agents: ['agent-builder', 'agent-approval'],
    tags: ['infrastructure', 'security', 'devops'],
  },
];
